version: '3.3'

services:
  content-conveyor:
    image: ghcr.io/panyukovnn/content-conveyor:${APP_TAG}
    container_name: content-conveyor
    ports:
      - 8084:8084
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: prom
    env_file:
      - /etc/common-config/config.env
    volumes:
      - ./application-prom.yaml:/application-prom.yaml